export const GET_RELATIONSHIPS_COMPLETE = "GET_RELATIONSHIPS_COMPLETE";
export const GET_RELATIONSHIPS = "GET_RELATIONSHIPS";
export const SEND_FRIEND_REQUEST_COMPLETE = "SEND_FRIEND_REQUEST_COMPLETE";
export const SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST";
export const REMOVE_FRIEND_COMPLETE = "REMOVE_FRIEND_COMPLETE";
export const REMOVE_FRIEND = "REMOVE_FRIEND";
export const OPEN_DM_COMPLETE = "OPEN_DM_COMPLETE";
export const OPEN_DM = "OPEN_DM";
