// https://discord.com/developers/docs/resources/channel#channel-object
import { DefaultReactionObject } from "../types/default-reaction-object";
import { ForumTagObject } from "../types/forum-tag-object";
import { OverwriteObject } from "../types/overwrite-object";
import { ThreadMemberObject } from "../types/thread-member-object";
import { ThreadMetaData } from "../types/thread-metadata";
import { User } from "./user";

class Channel {
  id: Snowflake;
  type: number;
  guild_id?: Snowflake;
  position?: number;
  permission_overwrites?: OverwriteObject[];
  name?: string | Maybe;
  topic?: string | Maybe;
  nsfw?: boolean;
  last_message_id?: Snowflake | Maybe;
  bitrate?: number;
  user_limit?: number;
  rate_limit_per_user?: number;
  recipients?: User[];
  icon?: string | Maybe;
  owner_id?: Snowflake;
  application_id?: Snowflake;
  managed?: boolean;
  parent_id?: Snowflake | Maybe;
  last_pin_timestamp?: string | Maybe;
  rtc_region?: string | Maybe;
  video_quality_mode?: number;
  message_count?: number;
  member_count?: number;
  thread_metadata?: ThreadMetaData;
  member?: ThreadMemberObject;
  default_auto_archive_duration?: number;
  permissions?: string;
  flags?: number;
  total_message_sent?: number;
  available_tags?: ForumTagObject[];
  applied_tags?: Snowflake[];
  default_reaction_emoji?: DefaultReactionObject | Maybe;
  default_thread_rate_limit_per_user?: number;
  default_sort_order?: number | Maybe;
  default_forum_layout?: number;

  constructor(opts: {
    id: Snowflake;
    type: number;
    guild_id?: Snowflake;
    position?: number;
    permission_overwrites?: OverwriteObject[];
    name?: string | Maybe;
    topic?: string | Maybe;
    nsfw?: boolean;
    last_message_id?: Snowflake | Maybe;
    bitrate?: number;
    user_limit?: number;
    rate_limit_per_user?: number;
    recipients?: User[];
    icon?: string | Maybe;
    owner_id?: Snowflake;
    application_id?: Snowflake;
    managed?: boolean;
    parent_id?: Snowflake | Maybe;
    last_pin_timestamp?: string | Maybe;
    rtc_region?: string | Maybe;
    video_quality_mode?: number;
    message_count?: number;
    member_count?: number;
    thread_metadata?: ThreadMetaData;
    member?: ThreadMemberObject;
    default_auto_archive_duration?: number;
    permissions?: string;
    flags?: number;
    total_message_sent?: number;
    available_tags?: ForumTagObject[];
    applied_tags?: Snowflake[];
    default_reaction_emoji?: DefaultReactionObject | Maybe;
    default_thread_rate_limit_per_user?: number;
    default_sort_order?: number | Maybe;
    default_forum_layout?: number;
  }) {
    this.id = opts.id;
    this.type = opts.type;
    this.guild_id = opts.guild_id;
    this.position = opts.position;
    this.permission_overwrites = opts.permission_overwrites;
    this.name = opts.name;
    this.topic = opts.topic;
    this.nsfw = opts.nsfw;
    this.last_message_id = opts.last_message_id;
    this.bitrate = opts.bitrate;
    this.user_limit = opts.user_limit;
    this.rate_limit_per_user = opts.rate_limit_per_user;
    this.recipients = opts.recipients;
    this.icon = opts.icon;
    this.owner_id = opts.owner_id;
    this.application_id = opts.application_id;
    this.managed = opts.managed;
    this.parent_id = opts.parent_id;
    this.last_pin_timestamp = opts.last_pin_timestamp;
    this.rtc_region = opts.rtc_region;
    this.video_quality_mode = opts.video_quality_mode;
    this.message_count = opts.message_count;
    this.member_count = opts.member_count;
    this.thread_metadata = opts.thread_metadata;
    this.member = opts.member;
    this.default_auto_archive_duration = opts.default_auto_archive_duration;
    this.permissions = opts.permissions;
    this.flags = opts.flags;
    this.total_message_sent = opts.total_message_sent;
    this.available_tags = opts.available_tags;
    this.applied_tags = opts.applied_tags;
    this.default_reaction_emoji = opts.default_reaction_emoji;
    this.default_thread_rate_limit_per_user =
      opts.default_thread_rate_limit_per_user;
    this.default_sort_order = opts.default_sort_order;
    this.default_forum_layout = opts.default_forum_layout;
  }
}
export default Channel;
