export const GET_MESSAGE_DATA = "GET_MESSAGE_DATA";
export const GET_MESSAGE_DATA_COMPLETE = "GET_MESSAGE_DATA_COMPLETE";
export const UPDATE_FETCHED_MESSAGES = "UPDATE_FETCHED_MESSAGES";
export const RESET_MESSAGE_DATA_COMPLETE = "RESET_MESSAGE_DATA_COMPLETE";
export const FILTER_MESSAGE = "FILTER_MESSAGE";
export const FILTER_MESSAGE_COMPLETE = "FILTER_MESSAGE_COMPLETE";
export const UPDATE_FILTERS_COMPLETE = "UPDATE_FILTERS_COMPLETE";
export const UPDATE_MESSAGE_SUCCESS = "UPDATE_MESSAGE_SUCCESS";
export const SET_SELECTED = "SET_SELECTED";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const SET_ATTACHMENT_MESSAGE_COMPLETE =
  "SET_ATTACHMENT_MESSAGE_COMPLETE";
