export const GET_MESSAGE_DATA = "GET_MESSAGE_DATA";
export const GET_MESSAGE_DATA_COMPLETE = "GET_MESSAGE_DATA_COMPLETE";
export const UPDATE_FETCHED_MESSAGES = "UPDATE_FETCHED_MESSAGES";
export const RESET_MESSAGE_DATA_COMPLETE = "RESET_MESSAGE_DATA_COMPLETE";
