export const GET_CHANNELS = "GET_CHANNELS";
export const GET_CHANNELS_COMPLETE = "GET_CHANNELS_COMPLETE";
export const SET_CHANNEL = "SET_CHANNEL";
export const RESET_CHANNEL_COMPLETE = "RESET_CHANNEL_COMPLETE";
