export const GET_CHANNELS = "GET_CHANNELS";
export const GET_CHANNELS_COMPLETE = "GET_CHANNELS_COMPLETE";
export const SET_CHANNEL = "SET_CHANNEL";
export const RESET_CHANNEL_COMPLETE = "RESET_CHANNEL_COMPLETE";
export const SET_PREFILTER_USERID = "SET_PREFILTER_USERID";
export const SET_SELECTED_EXPORT_CHANNELS = "SET_SELECTED_EXPORT_CHANNELS";
