export const SET_IS_EXPORTING = "SET_IS_EXPORTING";
export const SET_DOWNLOAD_IMAGES = "SET_DOWNLOAD_IMAGES";
export const SET_NAME = "SET_NAME";
export const SET_STATUS_TEXT = "SET_STATUS_TEXT";
export const INCREMENT_PROCESSING_TIME = "INCREMENT_PROCESSING_TIME";
export const START_PROCESSING_MESSAGES = "START_PROCESSING_MESSAGES";
export const PROCESSING_MESSAGES_COMPLETE = "PROCESSING_MESSAGES_COMPLETE";
